### ISSUE TITLE
[featurerequest] Refresh invalidated cache types by cronjob

### ISSUE THREAD

**Issue by nordcomputer** [mcspronko/selective-cache#18]
Is there something, that would speak against such functionality?

**Comment by mcspronko** [comment]
I believe that is a good idea.

**Comment by mcspronko** [comment]
It has to be managed via configuration and the list of cache updates should be visible via admin panel.

**Comment by nordcomputer** [comment]
I try to implement it, either tomorrow or next week - and of course, you should be able to configure the cronjob in the backend.

**Comment by nordcomputer** [comment]
ok, I opened a pull request.
As I don't know how to show a list of the finished cronjobs in the backend, the extension creates an own logfile (/var/log/pronko_selective_cache.log)
Also I tried to eliminate all warnings and errors regarding the magento-coding-standard.
As I don't speak Portuguese, I didn't add a translation for that.

**Comment by mcspronko** [comment]
Let me get back to you on the review

**Comment by nordcomputer** [comment]
I updated the pull request...waiting for another review...

**Comment by nordcomputer** [comment]
Are you going to create a new release? Would be nice to write this repo into my composer file ;-)

**Comment by mcspronko** [comment]
@nordcomputer I will indeed create a new release.

**Comment by nordcomputer** [comment]
@mcspronko - still waiting...

**Comment by mcspronko** [comment]
Closing as this feature has been implemented by @nordcomputer and merged to the master.
Thanks @nordcomputer

**Comment by nordcomputer** [comment]
thank you, but I am still waiting for a release, so I dont have to pull from main with my composer ;-)

**Comment by mcspronko** [comment]
@nordcomputer the new 1.2.0 release is now available.

**Comment by mcspronko** [comment]
What name should I use for the Contributors section?

**Comment by nordcomputer** [comment]
its already in there ;-)
![grafik](https://github.com/mcspronko/selective-cache/assets/13378398/25bd8882-7f79-47fe-8326-dfa05519546f)

**Comment by mcspronko** [comment]
Good, Good, thank you Mario :)
