### ISSUE TITLE
Refresh Link inside Cache notifications

### ISSUE THREAD

**Issue by mcspronko** [mcspronko/selective-cache#3]
Add a link inside Cache notifications to clear invalidated cache types. This will remove a need to go to a "Cache Management" page and refresh the cache.

This will reduce the number of clicks required to refresh cache from 2 to 1.

**Comment by gauravnewton** [comment]
Should i show clear cache link all the time in system alert or only when there exists any invalidated cache

**Comment by mcspronko** [comment]
@gauravnewton only when a notification message with the list of invalidated caches is shown.

**Comment by mcspronko** [comment]
Resolved
