### ISSUE TITLE
Add support for Magento 2.4.7

### ISSUE THREAD

**Issue by nordcomputer** [mcspronko/selective-cache#32]
I did not test yet, as composer tells me, that it has some compatibility issues with symfony/console:

```
Problem 1
    - symfony/console[v5.0.0, ..., v5.0.8] require php ^7.2.5 -> your php version (8.2.7) does not satisfy that requirement.
    - symfony/console[v4.0.0, ..., v4.4.8] require php ^7.1.3 -> your php version (8.2.7) does not satisfy that requirement.
    - Root composer.json requires magento/product-community-edition 2.4.7 -> satisfiable by magento/product-community-edition[2.4.7].
    - pronko/selective-cache 2.0.0 requires symfony/console ~4|~5 -> satisfiable by symfony/console[v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.36].
    - You can only install one version of a package, so only one of these can be installed: symfony/console[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.36, v6.0.0, ..., v6.4.6, v7.0.0, ..., v7.0.6].
    - magento/product-community-edition 2.4.7 requires symfony/console ^6.4 -> satisfiable by symfony/console[v6.4.0, ..., v6.4.6].
    - Root composer.json requires pronko/selective-cache ^2 -> satisfiable by pronko/selective-cache[2.0.0].
```

**Comment by mcspronko** [comment]
Hi Mario,
Thank you for the issue, it is pretty fast considering Magento 2.4.7 was out 3 days ago :).

**Comment by nordcomputer** [comment]
Hi Max,
I am still in the process of upgrading to 2.4.6 but I have an extra development branch for our shop where I try to keep everything up to the latest and greatest. So I gave the update to 2.4.7 a try ;-) 
And as I got the error, I thought I may just add an issue report for the record :)

**Comment by mcspronko** [comment]
Thank you, I can see the reason and will adjust the implementation accordingly.

**Comment by rjnicolai** [comment]
Hi Max,

Any idea when support for 2.4.7 (and php 8.3) will be available?

**Comment by mcspronko** [comment]
Hi @rjnicolai and @nordcomputer,
The [2.1.0](https://github.com/mcspronko/selective-cache/releases/tag/v2.1.0) provides support for Magento 2.4.7.
Thank you
